# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

company: GOATUI
title: GOAT UI
description: GOAT UI contains design system and most used web components built using Stencil. So you don't need to include any additional framework dependencies, You can simple import required component js, and right away start using it.
tagline: A light weight web component library
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goatui.com" # the base hostname & protocol for your site, e.g. http://example.com

email: contact@shivajivarma.com
author: Shivaji Varma
author_url: https://shivajivarma.com
twitter_username: goatui
github_username: goatui
github_project: components
npm_package: '@goatui/components'
script: 'https://unpkg.com/@goatui/components@0.10.2/dist/goatui/goatui.esm.js'
themeCss: 'https://unpkg.com/@goatui/components@0.10.2/dist/goatui/assets/styles/theme.css'

include:
  - .well-known

sass:
  style: compressed

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
  endings: all

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-spark

defaults:
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false
  - scope:
      path: "components/**/sections/**/*"
    values:
      sitemap: false
assets:
  compression: true
  assets:
    - "*.png"
    - "_scss/styles.scss"
  digest: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  plugins:
    css: { autoprefixer: { } }
    img: { optim: { } }

groups:
  - name: "Input Controls"
    components:
      - name: Input
        link: /component/input
        example: <goat-input type="text" placeholder="Enter you name here"></goat-input>
      - name: Textarea
        link: /component/textarea
        example: <goat-field-group><goat-label>Description</goat-label><goat-textarea></goat-textarea></goat-field-group>
      - name: Code Editor
        link: /component/code-editor
        img: /assets/img/code-editor.png

  - name: "Informational"
    components:
      - name: Alert
        link: /component/alert
        example: |
            <goat-notification state="success">
              <div slot='message'>Successful</div>
            </goat-notification>

  - name: "Content"
    components:
      - name: Avatar
        link: /component/avatar
        example: <goat-avatar name="Shivaji Varma"></goat-avatar>


  - name: "Navigation"
    components:
      - name: Link
        link: /component/link
        example: <goat-link>Link</goat-link>

components:
  - name: Dropdown
    link: /component/dropdown.html
    img: /assets/img/dropdown.png
  - name: Flow Designer
    link: /component/flow-designer.html
    img: /assets/img/image-not-found.png


  - name: List
    link: /component/list.html
    img: /assets/img/list.png

  - name: Select
    link: /component/select.html
    img: /assets/img/select.png

  - name: Table
    link: /component/table.html
    img: /assets/img/table.png



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
