title: P4RM UI - Local
script: '/assets/p4-ui-dev/build/p4rm-ui.esm.js'
themeCss: '/assets/p4-ui-dev/styles/theme.css'
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: GET, OPTIONS, HEAD
