script: '/assets/dev-build/build/goatui.esm.js'
themeCss: '/assets/dev-build/assets/styles/theme.css'
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: GET, OPTIONS, HEAD
