/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoatAvatar {
        "name": string;
        /**
          * Avatar size.
         */
        "size": string;
        "src": string;
    }
    interface GoatBadge {
        "content": string;
    }
    interface GoatCard {
        "shadowLevel": 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | undefined;
    }
    interface GoatCodeHighlighter {
        "language": 'markup' | 'css' | 'clike' | 'javascript' | 'abap' | 'actionscript' | 'ada' | 'apacheconf' | 'apl' | 'applescript' | 'arduino' | 'arff' | 'asciidoc' | 'asm6502' | 'aspnet' | 'autohotkey' | 'autoit' | 'bash' | 'basic' | 'batch' | 'bison' | 'brainfuck' | 'bro' | 'c' | 'csharp' | 'cpp' | 'coffeescript' | 'clojure' | 'crystal' | 'csp' | 'css-extras' | 'd' | 'dart' | 'diff' | 'django' | 'docker' | 'eiffel' | 'elixir' | 'elm' | 'erb' | 'erlang' | 'fsharp' | 'flow' | 'fortran' | 'gedcom' | 'gherkin' | 'git' | 'glsl' | 'gml' | 'go' | 'graphql' | 'groovy' | 'haml' | 'handlebars' | 'haskell' | 'haxe' | 'http' | 'hpkp' | 'hsts' | 'ichigojam' | 'icon' | 'inform7' | 'ini' | 'io' | 'j' | 'java' | 'jolie' | 'json' | 'julia' | 'keyman' | 'kotlin' | 'latex' | 'less' | 'liquid' | 'lisp' | 'livescript' | 'lolcode' | 'lua' | 'makefile' | 'markdown' | 'markup-templating' | 'matlab' | 'mel' | 'mizar' | 'monkey' | 'n4js' | 'nasm' | 'nginx' | 'nim' | 'nix' | 'nsis' | 'objectivec' | 'ocaml' | 'opencl' | 'oz' | 'parigp' | 'parser' | 'pascal' | 'perl' | 'php' | 'php-extras' | 'plsql' | 'powershell' | 'processing' | 'prolog' | 'properties' | 'protobuf' | 'pug' | 'puppet' | 'pure' | 'python' | 'q' | 'qore' | 'r' | 'jsx' | 'tsx' | 'renpy' | 'reason' | 'rest' | 'rip' | 'roboconf' | 'ruby' | 'rust' | 'sas' | 'sass' | 'scss' | 'scala' | 'scheme' | 'smalltalk' | 'smarty' | 'sql' | 'soy' | 'stylus' | 'swift' | 'tap' | 'tcl' | 'textile' | 'tt2' | 'twig' | 'typescript' | 'vbnet' | 'velocity' | 'verilog' | 'vhdl' | 'vim' | 'visual-basic' | 'wasm' | 'wiki' | 'xeora' | 'xojo' | 'xquery' | 'yaml';
        "lineNumbers": boolean;
        "value": string;
    }
    interface GoatSidenav {
        "showLoader": boolean;
    }
    interface GoatSidenavMenu {
        "empty": boolean;
        "emptyState": string;
        /**
          * Sets focus on first menu item. Use this method instead of the global `element.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        "value"?: string | number;
    }
    interface GoatSidenavMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * Menu item selection state.
         */
        "selected": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
}
declare global {
    interface HTMLGoatAvatarElement extends Components.GoatAvatar, HTMLStencilElement {
    }
    var HTMLGoatAvatarElement: {
        prototype: HTMLGoatAvatarElement;
        new (): HTMLGoatAvatarElement;
    };
    interface HTMLGoatBadgeElement extends Components.GoatBadge, HTMLStencilElement {
    }
    var HTMLGoatBadgeElement: {
        prototype: HTMLGoatBadgeElement;
        new (): HTMLGoatBadgeElement;
    };
    interface HTMLGoatCardElement extends Components.GoatCard, HTMLStencilElement {
    }
    var HTMLGoatCardElement: {
        prototype: HTMLGoatCardElement;
        new (): HTMLGoatCardElement;
    };
    interface HTMLGoatCodeHighlighterElement extends Components.GoatCodeHighlighter, HTMLStencilElement {
    }
    var HTMLGoatCodeHighlighterElement: {
        prototype: HTMLGoatCodeHighlighterElement;
        new (): HTMLGoatCodeHighlighterElement;
    };
    interface HTMLGoatSidenavElement extends Components.GoatSidenav, HTMLStencilElement {
    }
    var HTMLGoatSidenavElement: {
        prototype: HTMLGoatSidenavElement;
        new (): HTMLGoatSidenavElement;
    };
    interface HTMLGoatSidenavMenuElement extends Components.GoatSidenavMenu, HTMLStencilElement {
    }
    var HTMLGoatSidenavMenuElement: {
        prototype: HTMLGoatSidenavMenuElement;
        new (): HTMLGoatSidenavMenuElement;
    };
    interface HTMLGoatSidenavMenuItemElement extends Components.GoatSidenavMenuItem, HTMLStencilElement {
    }
    var HTMLGoatSidenavMenuItemElement: {
        prototype: HTMLGoatSidenavMenuItemElement;
        new (): HTMLGoatSidenavMenuItemElement;
    };
    interface HTMLElementTagNameMap {
        "goat-avatar": HTMLGoatAvatarElement;
        "goat-badge": HTMLGoatBadgeElement;
        "goat-card": HTMLGoatCardElement;
        "goat-code-highlighter": HTMLGoatCodeHighlighterElement;
        "goat-sidenav": HTMLGoatSidenavElement;
        "goat-sidenav-menu": HTMLGoatSidenavMenuElement;
        "goat-sidenav-menu-item": HTMLGoatSidenavMenuItemElement;
    }
}
declare namespace LocalJSX {
    interface GoatAvatar {
        "name"?: string;
        /**
          * Avatar size.
         */
        "size"?: string;
        "src"?: string;
    }
    interface GoatBadge {
        "content"?: string;
    }
    interface GoatCard {
        "shadowLevel"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | undefined;
    }
    interface GoatCodeHighlighter {
        "language"?: 'markup' | 'css' | 'clike' | 'javascript' | 'abap' | 'actionscript' | 'ada' | 'apacheconf' | 'apl' | 'applescript' | 'arduino' | 'arff' | 'asciidoc' | 'asm6502' | 'aspnet' | 'autohotkey' | 'autoit' | 'bash' | 'basic' | 'batch' | 'bison' | 'brainfuck' | 'bro' | 'c' | 'csharp' | 'cpp' | 'coffeescript' | 'clojure' | 'crystal' | 'csp' | 'css-extras' | 'd' | 'dart' | 'diff' | 'django' | 'docker' | 'eiffel' | 'elixir' | 'elm' | 'erb' | 'erlang' | 'fsharp' | 'flow' | 'fortran' | 'gedcom' | 'gherkin' | 'git' | 'glsl' | 'gml' | 'go' | 'graphql' | 'groovy' | 'haml' | 'handlebars' | 'haskell' | 'haxe' | 'http' | 'hpkp' | 'hsts' | 'ichigojam' | 'icon' | 'inform7' | 'ini' | 'io' | 'j' | 'java' | 'jolie' | 'json' | 'julia' | 'keyman' | 'kotlin' | 'latex' | 'less' | 'liquid' | 'lisp' | 'livescript' | 'lolcode' | 'lua' | 'makefile' | 'markdown' | 'markup-templating' | 'matlab' | 'mel' | 'mizar' | 'monkey' | 'n4js' | 'nasm' | 'nginx' | 'nim' | 'nix' | 'nsis' | 'objectivec' | 'ocaml' | 'opencl' | 'oz' | 'parigp' | 'parser' | 'pascal' | 'perl' | 'php' | 'php-extras' | 'plsql' | 'powershell' | 'processing' | 'prolog' | 'properties' | 'protobuf' | 'pug' | 'puppet' | 'pure' | 'python' | 'q' | 'qore' | 'r' | 'jsx' | 'tsx' | 'renpy' | 'reason' | 'rest' | 'rip' | 'roboconf' | 'ruby' | 'rust' | 'sas' | 'sass' | 'scss' | 'scala' | 'scheme' | 'smalltalk' | 'smarty' | 'sql' | 'soy' | 'stylus' | 'swift' | 'tap' | 'tcl' | 'textile' | 'tt2' | 'twig' | 'typescript' | 'vbnet' | 'velocity' | 'verilog' | 'vhdl' | 'vim' | 'visual-basic' | 'wasm' | 'wiki' | 'xeora' | 'xojo' | 'xquery' | 'yaml';
        "lineNumbers"?: boolean;
        "value"?: string;
    }
    interface GoatSidenav {
        "showLoader"?: boolean;
    }
    interface GoatSidenavMenu {
        "empty"?: boolean;
        "emptyState"?: string;
        "showLoader"?: boolean;
        "value"?: string | number;
    }
    interface GoatSidenavMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * Emitted when the menu item is clicked.
         */
        "onGoat:sidenav-menu-item-click"?: (event: CustomEvent<any>) => void;
        /**
          * Menu item selection state.
         */
        "selected"?: boolean;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface IntrinsicElements {
        "goat-avatar": GoatAvatar;
        "goat-badge": GoatBadge;
        "goat-card": GoatCard;
        "goat-code-highlighter": GoatCodeHighlighter;
        "goat-sidenav": GoatSidenav;
        "goat-sidenav-menu": GoatSidenavMenu;
        "goat-sidenav-menu-item": GoatSidenavMenuItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "goat-avatar": LocalJSX.GoatAvatar & JSXBase.HTMLAttributes<HTMLGoatAvatarElement>;
            "goat-badge": LocalJSX.GoatBadge & JSXBase.HTMLAttributes<HTMLGoatBadgeElement>;
            "goat-card": LocalJSX.GoatCard & JSXBase.HTMLAttributes<HTMLGoatCardElement>;
            "goat-code-highlighter": LocalJSX.GoatCodeHighlighter & JSXBase.HTMLAttributes<HTMLGoatCodeHighlighterElement>;
            "goat-sidenav": LocalJSX.GoatSidenav & JSXBase.HTMLAttributes<HTMLGoatSidenavElement>;
            "goat-sidenav-menu": LocalJSX.GoatSidenavMenu & JSXBase.HTMLAttributes<HTMLGoatSidenavMenuElement>;
            "goat-sidenav-menu-item": LocalJSX.GoatSidenavMenuItem & JSXBase.HTMLAttributes<HTMLGoatSidenavMenuItemElement>;
        }
    }
}
