/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoatAvatar {
        "name": string;
        /**
          * Avatar size.
         */
        "size": string;
        "src": string;
    }
    interface GoatBadge {
        "content": string;
    }
    interface GoatBreadcrumb {
    }
    interface GoatBreadcrumbItem {
        "active": boolean;
        /**
          * Hyperlink to navigate to on click.
         */
        "href": string;
        "position": string;
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target": string;
    }
    interface GoatButton {
        /**
          * If true, fits button width to its parent width. Defaults to `false`.
         */
        "block": boolean;
        "configAria": any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "disabledReason": string;
        /**
          * Hyperlink to navigate to on click.
         */
        "href": string;
        /**
          * Icon which will displayed on button. Possible values are bootstrap icon names.
         */
        "icon": string;
        /**
          * Icon position.
         */
        "iconEnd": boolean;
        /**
          * Button selection state.
         */
        "selected": boolean;
        /**
          * Sets blur on the native `button` in `goat-button`. Use this method instead of the global `button.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `button` in `goat-button`. Use this method instead of the global `button.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * Show loader.
         */
        "showLoader": boolean;
        /**
          * Button size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target": string;
        "triggerClick": () => Promise<void>;
        "variant": 'default' | 'light' | 'outline' | 'ghost' | 'link';
    }
    interface GoatButtonGroup {
    }
    interface GoatCalendar {
        "availableViews": any;
        "contextDate": any;
        "eventClickable": boolean;
        "events": any[];
        /**
          * Show loader.
         */
        "showLoader": boolean;
        "timezone": any;
        "view": string;
    }
    interface GoatCalendarColumnView {
        "contextDate": Date;
        "currentTime": Date;
        "days": number;
        "eventClickable": boolean;
        "events": any[];
        "view": string;
    }
    interface GoatCalendarColumnViewBackground {
        "columns": number;
    }
    interface GoatCalendarMonthView {
        "contextDate": Date;
        "currentTime": Date;
        "eventClickable": boolean;
        "events": any[];
    }
    interface GoatCalendarMonthViewBackground {
        "columns": number;
    }
    interface GoatCanvas {
        "lines": any[];
        "padding": number;
        "unitSize": number;
        "viewbox"?: string;
    }
    interface GoatCard {
        "shadowLevel": 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | undefined;
    }
    interface GoatCheckbox {
        "configAria": any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        "intermediate": boolean;
        /**
          * The checkbox label.
         */
        "label": string;
        /**
          * The input field name.
         */
        "name": string;
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        "rounded": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value": boolean;
    }
    interface GoatCodeEditor {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `onChange` event after each keystroke.
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        "language": 'javascript' | 'json' | 'html';
        "lineNumbers": 'off' | 'on';
        /**
          * The input field name.
         */
        "name": string;
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        "theme": 'vs-light' | 'vs-dark';
        /**
          * The input field value.
         */
        "value": string;
    }
    interface GoatCodeHighlighter {
        "language": string;
        "lineNumbers": boolean;
        "value": string;
    }
    interface GoatDatePicker {
        "configAria": any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        /**
          * The input field name.
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatDivider {
        "vertical": boolean;
    }
    interface GoatDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "isOpen": boolean;
        "items": any[];
        "positions": string;
        "setFocus": (elm?: HTMLElement) => Promise<void>;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface GoatEmptyState {
        "action": string;
        "actionDisabled": boolean;
        "actionUrl": string;
        "actionVariant": 'default' | 'light' | 'outline' | 'ghost' | 'link';
        "description": string;
        "headline": string;
        "illustration": 'no-document';
    }
    interface GoatFlowDesigner {
        "activities": any[];
        "blockSize": number;
        "disabled": boolean;
    }
    interface GoatFormControl {
        /**
          * The caption for the form control.
         */
        "caption": string;
        "error": string;
        "inline": boolean;
        /**
          * The label for the form control.
         */
        "label": string;
        /**
          * Whether the form control is required.
         */
        "required": boolean;
        "success": string;
        "warning": string;
    }
    interface GoatHeader {
    }
    interface GoatHeaderBrand {
        "href": string;
        "logo": string;
        "name": string;
        "subTitle": string;
    }
    interface GoatIcon {
        "name": string;
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GoatInput {
        /**
          * Indicates whether the value of the control can be automatically completed by the browser.
         */
        "autocomplete": 'on' | 'off';
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable": boolean;
        "configAria": any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        /**
          * The input field name.
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state": 'success' | 'error' | 'warning' | 'default';
        /**
          * The type of control to display. Possible values are: `"text"`, `"password"`, `"number"`, `"email"`, `"tel"`. Defaults to `"text"`.
         */
        "type": ('text' | 'password' | 'number' | 'email' | 'tel');
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatLink {
        /**
          * Hyperlink to navigate to on click.
         */
        "href": string;
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target": string;
        "triggerClick": () => Promise<void>;
    }
    interface GoatMenu {
        "empty": boolean;
        "emptyState": any;
        /**
          * Sets focus on first menu item. Use this method instead of the global `element.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        "value"?: string | number;
    }
    interface GoatMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * Menu item selection state.
         */
        "selected": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GoatNotification {
        "actionLabel": string;
        "actionName": string;
        "actionable": boolean;
        "dismissible": boolean;
        "lowContrast": boolean;
        "state": 'success' | 'error' | 'info' | 'warning';
    }
    interface GoatNotificationManager {
        "name": string;
        "position": 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
    }
    interface GoatSelect {
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable": boolean;
        "configAria": any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        "isOpen": boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items": any;
        "multiple": boolean;
        /**
          * The input field name.
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        "positions": string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search": 'none' | 'initial' | 'contains' | 'managed';
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `ion-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        /**
          * The select input size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state": 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value"?: string | number;
    }
    interface GoatSidenav {
        "showLoader": boolean;
    }
    interface GoatSidenavMenu {
        "empty": boolean;
        "emptyState": string;
        /**
          * Sets focus on first menu item. Use this method instead of the global `element.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        "value"?: string | number;
    }
    interface GoatSidenavMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * Menu item selection state.
         */
        "selected": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GoatSpinner {
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GoatSvg {
        "src": string;
    }
    interface GoatTab {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "disabledReason": string;
        /**
          * Icon which will displayed on button. Possible values are bootstrap icon names.
         */
        "icon": string;
        "label": string;
        /**
          * Button selection state.
         */
        "selected": boolean;
        "setFocus": () => Promise<void>;
        /**
          * Show loader.
         */
        "showLoader": boolean;
        /**
          * Button size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "target": string;
        "triggerClick": () => Promise<void>;
        "value": string;
    }
    interface GoatTabPanel {
        "active": boolean;
        "value": string;
    }
    interface GoatTable {
        /**
          * Grid columns configuration. [ {   "name":"name",   "label":"Name",   "width":300,   "fixed":true  }, {   "name":"age",   "label":"Age" } ]
         */
        "columns": any[];
        /**
          * Grid data to display on table [{  'id': '5e7118ddce4b3d577956457f',  'age': 21,  'name': 'John',  'company': 'India',  'email': 'john@example.com',  'phone': '+1 (839) 560-3581',  'address': '326 Irving Street, Grimsley, Texas, 4048'  }]
         */
        "data": any[];
        "emptyState": any;
        "keyField": string;
        "managed": boolean;
        "page": number;
        "pageSize": number;
        "paginate": boolean;
        "selectedRowKeys": string[];
        "selectionType": 'checkbox' | undefined;
        "sortBy": string;
        "sortOrder": 'asc' | 'desc';
        "sortable": boolean;
        "totalItems": any;
    }
    interface GoatTabs {
    }
    interface GoatTabsList {
        "managed": boolean;
        "variant": 'line' | 'contained';
    }
    interface GoatTag {
        "filter": boolean;
        /**
          * Text size.
         */
        "size": 'sm' | 'md';
        "value": string;
    }
    interface GoatText {
        /**
          * The heading level.
         */
        "level": 1 | 2 | 3 | 4 | 5;
        "shade": 'primary' | 'secondary' | 'tertiary';
        /**
          * Text size.
         */
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "type": 'heading' | 'paragraph' | 'text';
    }
    interface GoatTextarea {
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable": boolean;
        "configAria": any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goat:change` event after each keystroke.
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        /**
          * The input field name.
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        /**
          * Sets blur on the native `textarea` in `goat-textarea`. Use this method instead of the global `textarea.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `textarea` in `goat-textarea`. Use this method instead of the global `textarea.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state": 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value": string;
    }
    interface GoatTimePicker {
        "configAria": any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        /**
          * The input field name.
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatToast {
        "message": string;
        "state": 'success' | 'error' | 'info' | 'warning';
    }
}
export interface GoatButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatButtonElement;
}
export interface GoatCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatCalendarElement;
}
export interface GoatCalendarColumnViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatCalendarColumnViewElement;
}
export interface GoatCalendarMonthViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatCalendarMonthViewElement;
}
export interface GoatCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatCheckboxElement;
}
export interface GoatCodeEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatCodeEditorElement;
}
export interface GoatDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatDatePickerElement;
}
export interface GoatInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatInputElement;
}
export interface GoatMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatMenuItemElement;
}
export interface GoatNotificationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatNotificationElement;
}
export interface GoatSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatSelectElement;
}
export interface GoatSidenavMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatSidenavMenuItemElement;
}
export interface GoatTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatTabElement;
}
export interface GoatTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatTableElement;
}
export interface GoatTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatTagElement;
}
export interface GoatTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatTextareaElement;
}
export interface GoatTimePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatTimePickerElement;
}
declare global {
    interface HTMLGoatAvatarElement extends Components.GoatAvatar, HTMLStencilElement {
    }
    var HTMLGoatAvatarElement: {
        prototype: HTMLGoatAvatarElement;
        new (): HTMLGoatAvatarElement;
    };
    interface HTMLGoatBadgeElement extends Components.GoatBadge, HTMLStencilElement {
    }
    var HTMLGoatBadgeElement: {
        prototype: HTMLGoatBadgeElement;
        new (): HTMLGoatBadgeElement;
    };
    interface HTMLGoatBreadcrumbElement extends Components.GoatBreadcrumb, HTMLStencilElement {
    }
    var HTMLGoatBreadcrumbElement: {
        prototype: HTMLGoatBreadcrumbElement;
        new (): HTMLGoatBreadcrumbElement;
    };
    interface HTMLGoatBreadcrumbItemElement extends Components.GoatBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLGoatBreadcrumbItemElement: {
        prototype: HTMLGoatBreadcrumbItemElement;
        new (): HTMLGoatBreadcrumbItemElement;
    };
    interface HTMLGoatButtonElement extends Components.GoatButton, HTMLStencilElement {
    }
    var HTMLGoatButtonElement: {
        prototype: HTMLGoatButtonElement;
        new (): HTMLGoatButtonElement;
    };
    interface HTMLGoatButtonGroupElement extends Components.GoatButtonGroup, HTMLStencilElement {
    }
    var HTMLGoatButtonGroupElement: {
        prototype: HTMLGoatButtonGroupElement;
        new (): HTMLGoatButtonGroupElement;
    };
    interface HTMLGoatCalendarElement extends Components.GoatCalendar, HTMLStencilElement {
    }
    var HTMLGoatCalendarElement: {
        prototype: HTMLGoatCalendarElement;
        new (): HTMLGoatCalendarElement;
    };
    interface HTMLGoatCalendarColumnViewElement extends Components.GoatCalendarColumnView, HTMLStencilElement {
    }
    var HTMLGoatCalendarColumnViewElement: {
        prototype: HTMLGoatCalendarColumnViewElement;
        new (): HTMLGoatCalendarColumnViewElement;
    };
    interface HTMLGoatCalendarColumnViewBackgroundElement extends Components.GoatCalendarColumnViewBackground, HTMLStencilElement {
    }
    var HTMLGoatCalendarColumnViewBackgroundElement: {
        prototype: HTMLGoatCalendarColumnViewBackgroundElement;
        new (): HTMLGoatCalendarColumnViewBackgroundElement;
    };
    interface HTMLGoatCalendarMonthViewElement extends Components.GoatCalendarMonthView, HTMLStencilElement {
    }
    var HTMLGoatCalendarMonthViewElement: {
        prototype: HTMLGoatCalendarMonthViewElement;
        new (): HTMLGoatCalendarMonthViewElement;
    };
    interface HTMLGoatCalendarMonthViewBackgroundElement extends Components.GoatCalendarMonthViewBackground, HTMLStencilElement {
    }
    var HTMLGoatCalendarMonthViewBackgroundElement: {
        prototype: HTMLGoatCalendarMonthViewBackgroundElement;
        new (): HTMLGoatCalendarMonthViewBackgroundElement;
    };
    interface HTMLGoatCanvasElement extends Components.GoatCanvas, HTMLStencilElement {
    }
    var HTMLGoatCanvasElement: {
        prototype: HTMLGoatCanvasElement;
        new (): HTMLGoatCanvasElement;
    };
    interface HTMLGoatCardElement extends Components.GoatCard, HTMLStencilElement {
    }
    var HTMLGoatCardElement: {
        prototype: HTMLGoatCardElement;
        new (): HTMLGoatCardElement;
    };
    interface HTMLGoatCheckboxElement extends Components.GoatCheckbox, HTMLStencilElement {
    }
    var HTMLGoatCheckboxElement: {
        prototype: HTMLGoatCheckboxElement;
        new (): HTMLGoatCheckboxElement;
    };
    interface HTMLGoatCodeEditorElement extends Components.GoatCodeEditor, HTMLStencilElement {
    }
    var HTMLGoatCodeEditorElement: {
        prototype: HTMLGoatCodeEditorElement;
        new (): HTMLGoatCodeEditorElement;
    };
    interface HTMLGoatCodeHighlighterElement extends Components.GoatCodeHighlighter, HTMLStencilElement {
    }
    var HTMLGoatCodeHighlighterElement: {
        prototype: HTMLGoatCodeHighlighterElement;
        new (): HTMLGoatCodeHighlighterElement;
    };
    interface HTMLGoatDatePickerElement extends Components.GoatDatePicker, HTMLStencilElement {
    }
    var HTMLGoatDatePickerElement: {
        prototype: HTMLGoatDatePickerElement;
        new (): HTMLGoatDatePickerElement;
    };
    interface HTMLGoatDividerElement extends Components.GoatDivider, HTMLStencilElement {
    }
    var HTMLGoatDividerElement: {
        prototype: HTMLGoatDividerElement;
        new (): HTMLGoatDividerElement;
    };
    interface HTMLGoatDropdownElement extends Components.GoatDropdown, HTMLStencilElement {
    }
    var HTMLGoatDropdownElement: {
        prototype: HTMLGoatDropdownElement;
        new (): HTMLGoatDropdownElement;
    };
    interface HTMLGoatEmptyStateElement extends Components.GoatEmptyState, HTMLStencilElement {
    }
    var HTMLGoatEmptyStateElement: {
        prototype: HTMLGoatEmptyStateElement;
        new (): HTMLGoatEmptyStateElement;
    };
    interface HTMLGoatFlowDesignerElement extends Components.GoatFlowDesigner, HTMLStencilElement {
    }
    var HTMLGoatFlowDesignerElement: {
        prototype: HTMLGoatFlowDesignerElement;
        new (): HTMLGoatFlowDesignerElement;
    };
    interface HTMLGoatFormControlElement extends Components.GoatFormControl, HTMLStencilElement {
    }
    var HTMLGoatFormControlElement: {
        prototype: HTMLGoatFormControlElement;
        new (): HTMLGoatFormControlElement;
    };
    interface HTMLGoatHeaderElement extends Components.GoatHeader, HTMLStencilElement {
    }
    var HTMLGoatHeaderElement: {
        prototype: HTMLGoatHeaderElement;
        new (): HTMLGoatHeaderElement;
    };
    interface HTMLGoatHeaderBrandElement extends Components.GoatHeaderBrand, HTMLStencilElement {
    }
    var HTMLGoatHeaderBrandElement: {
        prototype: HTMLGoatHeaderBrandElement;
        new (): HTMLGoatHeaderBrandElement;
    };
    interface HTMLGoatIconElement extends Components.GoatIcon, HTMLStencilElement {
    }
    var HTMLGoatIconElement: {
        prototype: HTMLGoatIconElement;
        new (): HTMLGoatIconElement;
    };
    interface HTMLGoatInputElement extends Components.GoatInput, HTMLStencilElement {
    }
    var HTMLGoatInputElement: {
        prototype: HTMLGoatInputElement;
        new (): HTMLGoatInputElement;
    };
    interface HTMLGoatLinkElement extends Components.GoatLink, HTMLStencilElement {
    }
    var HTMLGoatLinkElement: {
        prototype: HTMLGoatLinkElement;
        new (): HTMLGoatLinkElement;
    };
    interface HTMLGoatMenuElement extends Components.GoatMenu, HTMLStencilElement {
    }
    var HTMLGoatMenuElement: {
        prototype: HTMLGoatMenuElement;
        new (): HTMLGoatMenuElement;
    };
    interface HTMLGoatMenuItemElement extends Components.GoatMenuItem, HTMLStencilElement {
    }
    var HTMLGoatMenuItemElement: {
        prototype: HTMLGoatMenuItemElement;
        new (): HTMLGoatMenuItemElement;
    };
    interface HTMLGoatNotificationElement extends Components.GoatNotification, HTMLStencilElement {
    }
    var HTMLGoatNotificationElement: {
        prototype: HTMLGoatNotificationElement;
        new (): HTMLGoatNotificationElement;
    };
    interface HTMLGoatNotificationManagerElement extends Components.GoatNotificationManager, HTMLStencilElement {
    }
    var HTMLGoatNotificationManagerElement: {
        prototype: HTMLGoatNotificationManagerElement;
        new (): HTMLGoatNotificationManagerElement;
    };
    interface HTMLGoatSelectElement extends Components.GoatSelect, HTMLStencilElement {
    }
    var HTMLGoatSelectElement: {
        prototype: HTMLGoatSelectElement;
        new (): HTMLGoatSelectElement;
    };
    interface HTMLGoatSidenavElement extends Components.GoatSidenav, HTMLStencilElement {
    }
    var HTMLGoatSidenavElement: {
        prototype: HTMLGoatSidenavElement;
        new (): HTMLGoatSidenavElement;
    };
    interface HTMLGoatSidenavMenuElement extends Components.GoatSidenavMenu, HTMLStencilElement {
    }
    var HTMLGoatSidenavMenuElement: {
        prototype: HTMLGoatSidenavMenuElement;
        new (): HTMLGoatSidenavMenuElement;
    };
    interface HTMLGoatSidenavMenuItemElement extends Components.GoatSidenavMenuItem, HTMLStencilElement {
    }
    var HTMLGoatSidenavMenuItemElement: {
        prototype: HTMLGoatSidenavMenuItemElement;
        new (): HTMLGoatSidenavMenuItemElement;
    };
    interface HTMLGoatSpinnerElement extends Components.GoatSpinner, HTMLStencilElement {
    }
    var HTMLGoatSpinnerElement: {
        prototype: HTMLGoatSpinnerElement;
        new (): HTMLGoatSpinnerElement;
    };
    interface HTMLGoatSvgElement extends Components.GoatSvg, HTMLStencilElement {
    }
    var HTMLGoatSvgElement: {
        prototype: HTMLGoatSvgElement;
        new (): HTMLGoatSvgElement;
    };
    interface HTMLGoatTabElement extends Components.GoatTab, HTMLStencilElement {
    }
    var HTMLGoatTabElement: {
        prototype: HTMLGoatTabElement;
        new (): HTMLGoatTabElement;
    };
    interface HTMLGoatTabPanelElement extends Components.GoatTabPanel, HTMLStencilElement {
    }
    var HTMLGoatTabPanelElement: {
        prototype: HTMLGoatTabPanelElement;
        new (): HTMLGoatTabPanelElement;
    };
    interface HTMLGoatTableElement extends Components.GoatTable, HTMLStencilElement {
    }
    var HTMLGoatTableElement: {
        prototype: HTMLGoatTableElement;
        new (): HTMLGoatTableElement;
    };
    interface HTMLGoatTabsElement extends Components.GoatTabs, HTMLStencilElement {
    }
    var HTMLGoatTabsElement: {
        prototype: HTMLGoatTabsElement;
        new (): HTMLGoatTabsElement;
    };
    interface HTMLGoatTabsListElement extends Components.GoatTabsList, HTMLStencilElement {
    }
    var HTMLGoatTabsListElement: {
        prototype: HTMLGoatTabsListElement;
        new (): HTMLGoatTabsListElement;
    };
    interface HTMLGoatTagElement extends Components.GoatTag, HTMLStencilElement {
    }
    var HTMLGoatTagElement: {
        prototype: HTMLGoatTagElement;
        new (): HTMLGoatTagElement;
    };
    interface HTMLGoatTextElement extends Components.GoatText, HTMLStencilElement {
    }
    var HTMLGoatTextElement: {
        prototype: HTMLGoatTextElement;
        new (): HTMLGoatTextElement;
    };
    interface HTMLGoatTextareaElement extends Components.GoatTextarea, HTMLStencilElement {
    }
    var HTMLGoatTextareaElement: {
        prototype: HTMLGoatTextareaElement;
        new (): HTMLGoatTextareaElement;
    };
    interface HTMLGoatTimePickerElement extends Components.GoatTimePicker, HTMLStencilElement {
    }
    var HTMLGoatTimePickerElement: {
        prototype: HTMLGoatTimePickerElement;
        new (): HTMLGoatTimePickerElement;
    };
    interface HTMLGoatToastElement extends Components.GoatToast, HTMLStencilElement {
    }
    var HTMLGoatToastElement: {
        prototype: HTMLGoatToastElement;
        new (): HTMLGoatToastElement;
    };
    interface HTMLElementTagNameMap {
        "goat-avatar": HTMLGoatAvatarElement;
        "goat-badge": HTMLGoatBadgeElement;
        "goat-breadcrumb": HTMLGoatBreadcrumbElement;
        "goat-breadcrumb-item": HTMLGoatBreadcrumbItemElement;
        "goat-button": HTMLGoatButtonElement;
        "goat-button-group": HTMLGoatButtonGroupElement;
        "goat-calendar": HTMLGoatCalendarElement;
        "goat-calendar-column-view": HTMLGoatCalendarColumnViewElement;
        "goat-calendar-column-view-background": HTMLGoatCalendarColumnViewBackgroundElement;
        "goat-calendar-month-view": HTMLGoatCalendarMonthViewElement;
        "goat-calendar-month-view-background": HTMLGoatCalendarMonthViewBackgroundElement;
        "goat-canvas": HTMLGoatCanvasElement;
        "goat-card": HTMLGoatCardElement;
        "goat-checkbox": HTMLGoatCheckboxElement;
        "goat-code-editor": HTMLGoatCodeEditorElement;
        "goat-code-highlighter": HTMLGoatCodeHighlighterElement;
        "goat-date-picker": HTMLGoatDatePickerElement;
        "goat-divider": HTMLGoatDividerElement;
        "goat-dropdown": HTMLGoatDropdownElement;
        "goat-empty-state": HTMLGoatEmptyStateElement;
        "goat-flow-designer": HTMLGoatFlowDesignerElement;
        "goat-form-control": HTMLGoatFormControlElement;
        "goat-header": HTMLGoatHeaderElement;
        "goat-header-brand": HTMLGoatHeaderBrandElement;
        "goat-icon": HTMLGoatIconElement;
        "goat-input": HTMLGoatInputElement;
        "goat-link": HTMLGoatLinkElement;
        "goat-menu": HTMLGoatMenuElement;
        "goat-menu-item": HTMLGoatMenuItemElement;
        "goat-notification": HTMLGoatNotificationElement;
        "goat-notification-manager": HTMLGoatNotificationManagerElement;
        "goat-select": HTMLGoatSelectElement;
        "goat-sidenav": HTMLGoatSidenavElement;
        "goat-sidenav-menu": HTMLGoatSidenavMenuElement;
        "goat-sidenav-menu-item": HTMLGoatSidenavMenuItemElement;
        "goat-spinner": HTMLGoatSpinnerElement;
        "goat-svg": HTMLGoatSvgElement;
        "goat-tab": HTMLGoatTabElement;
        "goat-tab-panel": HTMLGoatTabPanelElement;
        "goat-table": HTMLGoatTableElement;
        "goat-tabs": HTMLGoatTabsElement;
        "goat-tabs-list": HTMLGoatTabsListElement;
        "goat-tag": HTMLGoatTagElement;
        "goat-text": HTMLGoatTextElement;
        "goat-textarea": HTMLGoatTextareaElement;
        "goat-time-picker": HTMLGoatTimePickerElement;
        "goat-toast": HTMLGoatToastElement;
    }
}
declare namespace LocalJSX {
    interface GoatAvatar {
        "name"?: string;
        /**
          * Avatar size.
         */
        "size"?: string;
        "src"?: string;
    }
    interface GoatBadge {
        "content"?: string;
    }
    interface GoatBreadcrumb {
    }
    interface GoatBreadcrumbItem {
        "active"?: boolean;
        /**
          * Hyperlink to navigate to on click.
         */
        "href"?: string;
        "position"?: string;
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target"?: string;
    }
    interface GoatButton {
        /**
          * If true, fits button width to its parent width. Defaults to `false`.
         */
        "block"?: boolean;
        "configAria"?: any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "disabledReason"?: string;
        /**
          * Hyperlink to navigate to on click.
         */
        "href"?: string;
        /**
          * Icon which will displayed on button. Possible values are bootstrap icon names.
         */
        "icon"?: string;
        /**
          * Icon position.
         */
        "iconEnd"?: boolean;
        /**
          * On click of button, a CustomEvent 'goat:click' will be triggered.
         */
        "onGoat:click"?: (event: GoatButtonCustomEvent<any>) => void;
        /**
          * Button selection state.
         */
        "selected"?: boolean;
        /**
          * Show loader.
         */
        "showLoader"?: boolean;
        /**
          * Button size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target"?: string;
        "variant"?: 'default' | 'light' | 'outline' | 'ghost' | 'link';
    }
    interface GoatButtonGroup {
    }
    interface GoatCalendar {
        "availableViews"?: any;
        "contextDate"?: any;
        "eventClickable"?: boolean;
        "events"?: any[];
        "onGoat:calendar-event-click"?: (event: GoatCalendarCustomEvent<any>) => void;
        /**
          * Show loader.
         */
        "showLoader"?: boolean;
        "timezone"?: any;
        "view"?: string;
    }
    interface GoatCalendarColumnView {
        "contextDate"?: Date;
        "currentTime"?: Date;
        "days"?: number;
        "eventClickable"?: boolean;
        "events"?: any[];
        "onGoat:column-view-date-click"?: (event: GoatCalendarColumnViewCustomEvent<any>) => void;
        "onGoat:column-view-event-click"?: (event: GoatCalendarColumnViewCustomEvent<any>) => void;
        "view"?: string;
    }
    interface GoatCalendarColumnViewBackground {
        "columns"?: number;
    }
    interface GoatCalendarMonthView {
        "contextDate"?: Date;
        "currentTime"?: Date;
        "eventClickable"?: boolean;
        "events"?: any[];
        "onGoat:month-view-date-click"?: (event: GoatCalendarMonthViewCustomEvent<any>) => void;
        "onGoat:month-view-event-click"?: (event: GoatCalendarMonthViewCustomEvent<any>) => void;
    }
    interface GoatCalendarMonthViewBackground {
        "columns"?: number;
    }
    interface GoatCanvas {
        "lines"?: any[];
        "padding"?: number;
        "unitSize"?: number;
        "viewbox"?: string;
    }
    interface GoatCard {
        "shadowLevel"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | undefined;
    }
    interface GoatCheckbox {
        "configAria"?: any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "intermediate"?: boolean;
        /**
          * The checkbox label.
         */
        "label"?: string;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onGoat:blur"?: (event: GoatCheckboxCustomEvent<any>) => void;
        /**
          * On change of input a CustomEvent 'goat:change' will be triggered. Event details contains parent event, oldValue, newValue of input.
         */
        "onGoat:change"?: (event: GoatCheckboxCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGoat:focus"?: (event: GoatCheckboxCustomEvent<any>) => void;
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        "rounded"?: boolean;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value"?: boolean;
    }
    interface GoatCodeEditor {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `onChange` event after each keystroke.
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "language"?: 'javascript' | 'json' | 'html';
        "lineNumbers"?: 'off' | 'on';
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the value has changed..
         */
        "onGoat:change"?: (event: GoatCodeEditorCustomEvent<any>) => void;
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        "theme"?: 'vs-light' | 'vs-dark';
        /**
          * The input field value.
         */
        "value"?: string;
    }
    interface GoatCodeHighlighter {
        "language"?: string;
        "lineNumbers"?: boolean;
        "value"?: string;
    }
    interface GoatDatePicker {
        "configAria"?: any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onGoat:blur"?: (event: GoatDatePickerCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onGoat:change"?: (event: GoatDatePickerCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGoat:focus"?: (event: GoatDatePickerCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat:input"?: (event: GoatDatePickerCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatDivider {
        "vertical"?: boolean;
    }
    interface GoatDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "isOpen"?: boolean;
        "items"?: any[];
        "positions"?: string;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface GoatEmptyState {
        "action"?: string;
        "actionDisabled"?: boolean;
        "actionUrl"?: string;
        "actionVariant"?: 'default' | 'light' | 'outline' | 'ghost' | 'link';
        "description"?: string;
        "headline"?: string;
        "illustration"?: 'no-document';
    }
    interface GoatFlowDesigner {
        "activities"?: any[];
        "blockSize"?: number;
        "disabled"?: boolean;
    }
    interface GoatFormControl {
        /**
          * The caption for the form control.
         */
        "caption"?: string;
        "error"?: string;
        "inline"?: boolean;
        /**
          * The label for the form control.
         */
        "label"?: string;
        /**
          * Whether the form control is required.
         */
        "required"?: boolean;
        "success"?: string;
        "warning"?: string;
    }
    interface GoatHeader {
    }
    interface GoatHeaderBrand {
        "href"?: string;
        "logo"?: string;
        "name"?: string;
        "subTitle"?: string;
    }
    interface GoatIcon {
        "name"?: string;
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GoatInput {
        /**
          * Indicates whether the value of the control can be automatically completed by the browser.
         */
        "autocomplete"?: 'on' | 'off';
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable"?: boolean;
        "configAria"?: any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onGoat:blur"?: (event: GoatInputCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onGoat:change"?: (event: GoatInputCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGoat:focus"?: (event: GoatInputCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat:input"?: (event: GoatInputCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state"?: 'success' | 'error' | 'warning' | 'default';
        /**
          * The type of control to display. Possible values are: `"text"`, `"password"`, `"number"`, `"email"`, `"tel"`. Defaults to `"text"`.
         */
        "type"?: ('text' | 'password' | 'number' | 'email' | 'tel');
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatLink {
        /**
          * Hyperlink to navigate to on click.
         */
        "href"?: string;
        /**
          * Sets or retrieves the window or frame at which to target content.
         */
        "target"?: string;
    }
    interface GoatMenu {
        "empty"?: boolean;
        "emptyState"?: any;
        "showLoader"?: boolean;
        "value"?: string | number;
    }
    interface GoatMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * Emitted when the menu item is clicked.
         */
        "onGoat:menu-item-click"?: (event: GoatMenuItemCustomEvent<any>) => void;
        /**
          * Menu item selection state.
         */
        "selected"?: boolean;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GoatNotification {
        "actionLabel"?: string;
        "actionName"?: string;
        "actionable"?: boolean;
        "dismissible"?: boolean;
        "lowContrast"?: boolean;
        "onGoat:dismiss"?: (event: GoatNotificationCustomEvent<any>) => void;
        "state"?: 'success' | 'error' | 'info' | 'warning';
    }
    interface GoatNotificationManager {
        "name"?: string;
        "position"?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
    }
    interface GoatSelect {
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable"?: boolean;
        "configAria"?: any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "isOpen"?: boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items"?: any;
        "multiple"?: boolean;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the action button is clicked..
         */
        "onGoat:action-click"?: (event: GoatSelectCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onGoat:change"?: (event: GoatSelectCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat:search"?: (event: GoatSelectCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        "positions"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search"?: 'none' | 'initial' | 'contains' | 'managed';
        "showLoader"?: boolean;
        /**
          * The select input size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state"?: 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value"?: string | number;
    }
    interface GoatSidenav {
        "showLoader"?: boolean;
    }
    interface GoatSidenavMenu {
        "empty"?: boolean;
        "emptyState"?: string;
        "showLoader"?: boolean;
        "value"?: string | number;
    }
    interface GoatSidenavMenuItem {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * Emitted when the menu item is clicked.
         */
        "onGoat:sidenav-menu-item-click"?: (event: GoatSidenavMenuItemCustomEvent<any>) => void;
        /**
          * Menu item selection state.
         */
        "selected"?: boolean;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GoatSpinner {
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GoatSvg {
        "src"?: string;
    }
    interface GoatTab {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "disabledReason"?: string;
        /**
          * Icon which will displayed on button. Possible values are bootstrap icon names.
         */
        "icon"?: string;
        "label"?: string;
        /**
          * On click of tab, a CustomEvent 'goat:tab-click' will be triggered.
         */
        "onGoat:tab-click"?: (event: GoatTabCustomEvent<any>) => void;
        /**
          * Button selection state.
         */
        "selected"?: boolean;
        /**
          * Show loader.
         */
        "showLoader"?: boolean;
        /**
          * Button size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "target"?: string;
        "value"?: string;
    }
    interface GoatTabPanel {
        "active"?: boolean;
        "value"?: string;
    }
    interface GoatTable {
        /**
          * Grid columns configuration. [ {   "name":"name",   "label":"Name",   "width":300,   "fixed":true  }, {   "name":"age",   "label":"Age" } ]
         */
        "columns"?: any[];
        /**
          * Grid data to display on table [{  'id': '5e7118ddce4b3d577956457f',  'age': 21,  'name': 'John',  'company': 'India',  'email': 'john@example.com',  'phone': '+1 (839) 560-3581',  'address': '326 Irving Street, Grimsley, Texas, 4048'  }]
         */
        "data"?: any[];
        "emptyState"?: any;
        "keyField"?: string;
        "managed"?: boolean;
        "onGoat:page"?: (event: GoatTableCustomEvent<any>) => void;
        "onGoat:sort"?: (event: GoatTableCustomEvent<any>) => void;
        "onGoat:table-cell-click"?: (event: GoatTableCustomEvent<any>) => void;
        "onGoat:table-select-change"?: (event: GoatTableCustomEvent<any>) => void;
        "page"?: number;
        "pageSize"?: number;
        "paginate"?: boolean;
        "selectedRowKeys"?: string[];
        "selectionType"?: 'checkbox' | undefined;
        "sortBy"?: string;
        "sortOrder"?: 'asc' | 'desc';
        "sortable"?: boolean;
        "totalItems"?: any;
    }
    interface GoatTabs {
    }
    interface GoatTabsList {
        "managed"?: boolean;
        "variant"?: 'line' | 'contained';
    }
    interface GoatTag {
        "filter"?: boolean;
        "onGoat:click"?: (event: GoatTagCustomEvent<any>) => void;
        "onGoat:tag-dismiss"?: (event: GoatTagCustomEvent<any>) => void;
        /**
          * Text size.
         */
        "size"?: 'sm' | 'md';
        "value"?: string;
    }
    interface GoatText {
        /**
          * The heading level.
         */
        "level"?: 1 | 2 | 3 | 4 | 5;
        "shade"?: 'primary' | 'secondary' | 'tertiary';
        /**
          * Text size.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "type"?: 'heading' | 'paragraph' | 'text';
    }
    interface GoatTextarea {
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable"?: boolean;
        "configAria"?: any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goat:change` event after each keystroke.
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the action button is clicked.
         */
        "onGoat:action-click"?: (event: GoatTextareaCustomEvent<any>) => void;
        /**
          * Emitted when the input loses focus.
         */
        "onGoat:blur"?: (event: GoatTextareaCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed..
         */
        "onGoat:change"?: (event: GoatTextareaCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGoat:focus"?: (event: GoatTextareaCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat:input"?: (event: GoatTextareaCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state"?: 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value"?: string;
    }
    interface GoatTimePicker {
        "configAria"?: any;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The input field name.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onGoat:blur"?: (event: GoatTimePickerCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onGoat:change"?: (event: GoatTimePickerCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGoat:focus"?: (event: GoatTimePickerCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat:input"?: (event: GoatTimePickerCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input field value.
         */
        "value"?: string | number | null;
    }
    interface GoatToast {
        "message"?: string;
        "state"?: 'success' | 'error' | 'info' | 'warning';
    }
    interface IntrinsicElements {
        "goat-avatar": GoatAvatar;
        "goat-badge": GoatBadge;
        "goat-breadcrumb": GoatBreadcrumb;
        "goat-breadcrumb-item": GoatBreadcrumbItem;
        "goat-button": GoatButton;
        "goat-button-group": GoatButtonGroup;
        "goat-calendar": GoatCalendar;
        "goat-calendar-column-view": GoatCalendarColumnView;
        "goat-calendar-column-view-background": GoatCalendarColumnViewBackground;
        "goat-calendar-month-view": GoatCalendarMonthView;
        "goat-calendar-month-view-background": GoatCalendarMonthViewBackground;
        "goat-canvas": GoatCanvas;
        "goat-card": GoatCard;
        "goat-checkbox": GoatCheckbox;
        "goat-code-editor": GoatCodeEditor;
        "goat-code-highlighter": GoatCodeHighlighter;
        "goat-date-picker": GoatDatePicker;
        "goat-divider": GoatDivider;
        "goat-dropdown": GoatDropdown;
        "goat-empty-state": GoatEmptyState;
        "goat-flow-designer": GoatFlowDesigner;
        "goat-form-control": GoatFormControl;
        "goat-header": GoatHeader;
        "goat-header-brand": GoatHeaderBrand;
        "goat-icon": GoatIcon;
        "goat-input": GoatInput;
        "goat-link": GoatLink;
        "goat-menu": GoatMenu;
        "goat-menu-item": GoatMenuItem;
        "goat-notification": GoatNotification;
        "goat-notification-manager": GoatNotificationManager;
        "goat-select": GoatSelect;
        "goat-sidenav": GoatSidenav;
        "goat-sidenav-menu": GoatSidenavMenu;
        "goat-sidenav-menu-item": GoatSidenavMenuItem;
        "goat-spinner": GoatSpinner;
        "goat-svg": GoatSvg;
        "goat-tab": GoatTab;
        "goat-tab-panel": GoatTabPanel;
        "goat-table": GoatTable;
        "goat-tabs": GoatTabs;
        "goat-tabs-list": GoatTabsList;
        "goat-tag": GoatTag;
        "goat-text": GoatText;
        "goat-textarea": GoatTextarea;
        "goat-time-picker": GoatTimePicker;
        "goat-toast": GoatToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "goat-avatar": LocalJSX.GoatAvatar & JSXBase.HTMLAttributes<HTMLGoatAvatarElement>;
            "goat-badge": LocalJSX.GoatBadge & JSXBase.HTMLAttributes<HTMLGoatBadgeElement>;
            "goat-breadcrumb": LocalJSX.GoatBreadcrumb & JSXBase.HTMLAttributes<HTMLGoatBreadcrumbElement>;
            "goat-breadcrumb-item": LocalJSX.GoatBreadcrumbItem & JSXBase.HTMLAttributes<HTMLGoatBreadcrumbItemElement>;
            "goat-button": LocalJSX.GoatButton & JSXBase.HTMLAttributes<HTMLGoatButtonElement>;
            "goat-button-group": LocalJSX.GoatButtonGroup & JSXBase.HTMLAttributes<HTMLGoatButtonGroupElement>;
            "goat-calendar": LocalJSX.GoatCalendar & JSXBase.HTMLAttributes<HTMLGoatCalendarElement>;
            "goat-calendar-column-view": LocalJSX.GoatCalendarColumnView & JSXBase.HTMLAttributes<HTMLGoatCalendarColumnViewElement>;
            "goat-calendar-column-view-background": LocalJSX.GoatCalendarColumnViewBackground & JSXBase.HTMLAttributes<HTMLGoatCalendarColumnViewBackgroundElement>;
            "goat-calendar-month-view": LocalJSX.GoatCalendarMonthView & JSXBase.HTMLAttributes<HTMLGoatCalendarMonthViewElement>;
            "goat-calendar-month-view-background": LocalJSX.GoatCalendarMonthViewBackground & JSXBase.HTMLAttributes<HTMLGoatCalendarMonthViewBackgroundElement>;
            "goat-canvas": LocalJSX.GoatCanvas & JSXBase.HTMLAttributes<HTMLGoatCanvasElement>;
            "goat-card": LocalJSX.GoatCard & JSXBase.HTMLAttributes<HTMLGoatCardElement>;
            "goat-checkbox": LocalJSX.GoatCheckbox & JSXBase.HTMLAttributes<HTMLGoatCheckboxElement>;
            "goat-code-editor": LocalJSX.GoatCodeEditor & JSXBase.HTMLAttributes<HTMLGoatCodeEditorElement>;
            "goat-code-highlighter": LocalJSX.GoatCodeHighlighter & JSXBase.HTMLAttributes<HTMLGoatCodeHighlighterElement>;
            "goat-date-picker": LocalJSX.GoatDatePicker & JSXBase.HTMLAttributes<HTMLGoatDatePickerElement>;
            "goat-divider": LocalJSX.GoatDivider & JSXBase.HTMLAttributes<HTMLGoatDividerElement>;
            "goat-dropdown": LocalJSX.GoatDropdown & JSXBase.HTMLAttributes<HTMLGoatDropdownElement>;
            "goat-empty-state": LocalJSX.GoatEmptyState & JSXBase.HTMLAttributes<HTMLGoatEmptyStateElement>;
            "goat-flow-designer": LocalJSX.GoatFlowDesigner & JSXBase.HTMLAttributes<HTMLGoatFlowDesignerElement>;
            "goat-form-control": LocalJSX.GoatFormControl & JSXBase.HTMLAttributes<HTMLGoatFormControlElement>;
            "goat-header": LocalJSX.GoatHeader & JSXBase.HTMLAttributes<HTMLGoatHeaderElement>;
            "goat-header-brand": LocalJSX.GoatHeaderBrand & JSXBase.HTMLAttributes<HTMLGoatHeaderBrandElement>;
            "goat-icon": LocalJSX.GoatIcon & JSXBase.HTMLAttributes<HTMLGoatIconElement>;
            "goat-input": LocalJSX.GoatInput & JSXBase.HTMLAttributes<HTMLGoatInputElement>;
            "goat-link": LocalJSX.GoatLink & JSXBase.HTMLAttributes<HTMLGoatLinkElement>;
            "goat-menu": LocalJSX.GoatMenu & JSXBase.HTMLAttributes<HTMLGoatMenuElement>;
            "goat-menu-item": LocalJSX.GoatMenuItem & JSXBase.HTMLAttributes<HTMLGoatMenuItemElement>;
            "goat-notification": LocalJSX.GoatNotification & JSXBase.HTMLAttributes<HTMLGoatNotificationElement>;
            "goat-notification-manager": LocalJSX.GoatNotificationManager & JSXBase.HTMLAttributes<HTMLGoatNotificationManagerElement>;
            "goat-select": LocalJSX.GoatSelect & JSXBase.HTMLAttributes<HTMLGoatSelectElement>;
            "goat-sidenav": LocalJSX.GoatSidenav & JSXBase.HTMLAttributes<HTMLGoatSidenavElement>;
            "goat-sidenav-menu": LocalJSX.GoatSidenavMenu & JSXBase.HTMLAttributes<HTMLGoatSidenavMenuElement>;
            "goat-sidenav-menu-item": LocalJSX.GoatSidenavMenuItem & JSXBase.HTMLAttributes<HTMLGoatSidenavMenuItemElement>;
            "goat-spinner": LocalJSX.GoatSpinner & JSXBase.HTMLAttributes<HTMLGoatSpinnerElement>;
            "goat-svg": LocalJSX.GoatSvg & JSXBase.HTMLAttributes<HTMLGoatSvgElement>;
            "goat-tab": LocalJSX.GoatTab & JSXBase.HTMLAttributes<HTMLGoatTabElement>;
            "goat-tab-panel": LocalJSX.GoatTabPanel & JSXBase.HTMLAttributes<HTMLGoatTabPanelElement>;
            "goat-table": LocalJSX.GoatTable & JSXBase.HTMLAttributes<HTMLGoatTableElement>;
            "goat-tabs": LocalJSX.GoatTabs & JSXBase.HTMLAttributes<HTMLGoatTabsElement>;
            "goat-tabs-list": LocalJSX.GoatTabsList & JSXBase.HTMLAttributes<HTMLGoatTabsListElement>;
            "goat-tag": LocalJSX.GoatTag & JSXBase.HTMLAttributes<HTMLGoatTagElement>;
            "goat-text": LocalJSX.GoatText & JSXBase.HTMLAttributes<HTMLGoatTextElement>;
            "goat-textarea": LocalJSX.GoatTextarea & JSXBase.HTMLAttributes<HTMLGoatTextareaElement>;
            "goat-time-picker": LocalJSX.GoatTimePicker & JSXBase.HTMLAttributes<HTMLGoatTimePickerElement>;
            "goat-toast": LocalJSX.GoatToast & JSXBase.HTMLAttributes<HTMLGoatToastElement>;
        }
    }
}
