name: Node CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - 'releases/**'

jobs:
  build:

    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm run build
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./docs/reports/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
